# Generated by Django 5.1.3 on 2025-09-03 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='quantity',
        ),
        migrations.AddField(
            model_name='ingredients',
            name='required_ingredients',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='Recipe_App.user'),
        ),
    ]
